export const COUNTRY_OPTIONS = [
  "United States of America",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Greece",
  "Turkey",
  "United Arab Emirates",
  "Saudi Arabia",
  "Egypt",
  "Lebanon",
  "Jordan",
  "India",
  "Japan",
  "South Korea",
  "Indonesia",
  "Brazil",
  "Mexico",
  "Other",
] as const;
