export const COUNTRY_OPTIONS = [
  "United States of America",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Greece",
  "Turkey",
  "United Arab Emirates",
  "Saudi Arabia",
  "Egypt",
  "Lebanon",
  "Jordan",
  "India",
  "Japan",
  "South Korea",
  "Indonesia",
  "Brazil",
  "Mexico",
  "Other",
] as const;

export const COUNTRY_DIAL_OPTIONS = [
  { country: "United States of America", code: "+1" },
  { country: "United Kingdom", code: "+44" },
  { country: "Canada", code: "+1" },
  { country: "Australia", code: "+61" },
  { country: "Germany", code: "+49" },
  { country: "France", code: "+33" },
  { country: "Italy", code: "+39" },
  { country: "Spain", code: "+34" },
  { country: "Greece", code: "+30" },
  { country: "Turkey", code: "+90" },
  { country: "United Arab Emirates", code: "+971" },
  { country: "Saudi Arabia", code: "+966" },
  { country: "Egypt", code: "+20" },
  { country: "Lebanon", code: "+961" },
  { country: "Jordan", code: "+962" },
  { country: "India", code: "+91" },
  { country: "Japan", code: "+81" },
  { country: "South Korea", code: "+82" },
  { country: "Indonesia", code: "+62" },
  { country: "Brazil", code: "+55" },
  { country: "Mexico", code: "+52" },
  { country: "Other", code: "+000" },
] as const;
